Top PyPI sdists for Mon Sep 15 05:58:37 UTC 2025

diff --git a/extracted/ll/llama-index/PKG-INFO b/extracted/ll/llama-index/PKG-INFO
--- a/extracted/ll/llama-index/PKG-INFO
+++ b/extracted/ll/llama-index/PKG-INFO
@@ -1,6 +1,6 @@
 Metadata-Version: 2.4
 Name: llama-index
-Version: 0.14.0
+Version: 0.14.1
 Summary: Interface between LLMs and your data
 Project-URL: Documentation, https://docs.llamaindex.ai/en/stable/
 Project-URL: Homepage, https://llamaindex.ai
@@ -15,7 +15,7 @@ Classifier: Topic :: Software Development :: Libraries :: Application Frameworks
 Classifier: Topic :: Software Development :: Libraries :: Python Modules
 Requires-Python: <4.0,>=3.9
 Requires-Dist: llama-index-cli<0.6,>=0.5.0
-Requires-Dist: llama-index-core<0.15,>=0.13.6
+Requires-Dist: llama-index-core<0.15,>=0.14.1
 Requires-Dist: llama-index-embeddings-openai<0.6,>=0.5.0
 Requires-Dist: llama-index-indices-managed-llama-cloud>=0.4.0
 Requires-Dist: llama-index-llms-openai<0.6,>=0.5.0
@@ -212,6 +212,25 @@ file in each of the package's folders.
 cd <desired-package-folder>
 pip install poetry
 poetry install --with dev
+```
+
+## A note on Verification of Build Assets
+
+By default, `llama-index-core` includes a `_static` folder that contains the nltk and tiktoken cache that is included with the package installation. This ensures that you can easily run `llama-index` in environments with restrictive disk access permissions at runtime.
+
+To verify that these files are safe and valid, we use the github `attest-build-provenance` action. This action will verify that the files in the `_static` folder are the same as the files in the `llama-index-core/llama_index/core/_static` folder.
+
+To verify this, you can run the following script (pointing to your installed package):
+
+```bash
+#!/bin/bash
+STATIC_DIR="venv/lib/python3.13/site-packages/llama_index/core/_static"
+REPO="run-llama/llama_index"
+
+find "$STATIC_DIR" -type f | while read -r file; do
+    echo "Verifying: $file"
+    gh attestation verify "$file" -R "$REPO" || echo "Failed to verify: $file"
+done
 ```
 
 ## 📖 Citation
